/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Lwg_Loding from "./script/Frame/Lwg_Loding"
import GameUI from "./script/GameUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scene/UILoding.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Frame/Lwg_Loding.ts",Lwg_Loding);
        reg("script/GameUI.ts",GameUI);
    }
}
GameConfig.init();